<?xml version="1.0" encoding="UTF-8"?><testrun name="MyAssertTest" project="junit_in_5_steps" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.in28minutes.junit.MyAssertTest" time="0.021" displayname="MyAssertTest" uniqueid="[engine:junit-jupiter]/[class:com.in28minutes.junit.MyAssertTest]">
    <testcase name="test" classname="com.in28minutes.junit.MyAssertTest" time="0.021" displayname="test()" uniqueid="[engine:junit-jupiter]/[class:com.in28minutes.junit.MyAssertTest]/[method:test()]">
      <failure>java.lang.AssertionError: Something went wrong&#13;
	at org.junit.Assert.fail(Assert.java:89)&#13;
	at org.junit.Assert.assertTrue(Assert.java:42)&#13;
	at com.in28minutes.junit.MyAssertTest.test(MyAssertTest.java:20)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
